features:
  versions:
    - HTTP_VERSION_1
  protocols:
    - PROTOCOL_CONNECT
  codecs:
    - CODEC_PROTO
  compressions:
    - COMPRESSION_IDENTITY
  streamTypes:
    - STREAM_TYPE_UNARY
  supportsTls: false
  supportsTrailers: false
